# Generated by Django 4.1.1 on 2022-10-13 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=700)),
                ('image', models.URLField(max_length=400)),
                ('catagory', models.CharField(max_length=20)),
                ('bid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auctionbid', to='auctions.bid')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auctionlistings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
